(import cons car cdr null null? "cons.lisp")
(import true false "bool.lisp")

(assert-equal true (null? null))
(assert-equal true (null (lambda (car cdr) false)))
(assert-equal false (null? (cons null null)))
(assert-equal false (null? (cons null null)))
(assert-equal false ((cons null null) (lambda (car cdr) false)))
(assert-equal false ((lambda (car cdr) false) null null))
(assert-equal true (null? (car (cons null null))))
(assert-equal true (null? (cdr (cons null null))))
(assert-equal true (null? null))
