#pragma once

x_fn_1_t x_assert;
x_fn_1_t x_assert_zh;
x_fn_1_t x_assert_not;
x_fn_1_t x_assert_not_zh;
x_fn_2_t x_assert_equal;
x_fn_2_t x_assert_equal_zh;
x_fn_2_t x_assert_not_equal;
x_fn_2_t x_assert_not_equal_zh;
x_fn_2_t x_assert_with_location;
x_fn_2_t x_assert_with_location_zh;
x_fn_2_t x_assert_not_with_location;
x_fn_2_t x_assert_not_with_location_zh;
x_fn_3_t x_assert_equal_with_location;
x_fn_3_t x_assert_equal_with_location_zh;
x_fn_3_t x_assert_not_equal_with_location;
x_fn_3_t x_assert_not_equal_with_location_zh;