#pragma once

#define TH_DISPATCH_CASES \
  case OP_MOVE: goto th_move; \
  case OP_LOAD_INT: goto th_load_value; \
  case OP_LOAD_FLOAT: goto th_load_value; \
  case OP_LOAD_STRING: goto th_load_value; \
  case OP_LOAD_SYMBOL: goto th_load_value; \
  case OP_LOAD_CLOSURE: goto th_load_value; \
  case OP_MAKE_CLOSURE: goto th_make_closure; \
  case OP_STORE_CLOSURE_ARG: goto th_store_closure_arg; \
  case OP_LOAD_RESULT: goto th_load_result; \
  case OP_LOAD_GLOBAL: goto th_load_global; \
  case OP_STORE_GLOBAL: goto th_store_global; \
  case OP_RETURN: goto th_return; \
  case OP_RETURN_VOID: goto th_return_void; \
  case OP_GC: goto th_gc; \
  case OP_CALL_0: goto th_call_0; \
  case OP_CALL_1: goto th_call_1; \
  case OP_CALL_2: goto th_call_2; \
  case OP_CALL_3: goto th_call_3; \
  case OP_CALL_4: goto th_call_4; \
  case OP_CALL_5: goto th_call_5; \
  case OP_CALL_6: goto th_call_6; \
  case OP_CALL_PRIM_0: goto th_call_prim_0; \
  case OP_CALL_PRIM_1: goto th_call_prim_1; \
  case OP_CALL_PRIM_2: goto th_call_prim_2; \
  case OP_CALL_PRIM_3: goto th_call_prim_3; \
  case OP_CALL_PRIM_4: goto th_call_prim_4; \
  case OP_CALL_PRIM_5: goto th_call_prim_5; \
  case OP_CALL_PRIM_6: goto th_call_prim_6; \
  case OP_TAIL_CALL_0: goto th_tail_call_0; \
  case OP_TAIL_CALL_1: goto th_tail_call_1; \
  case OP_TAIL_CALL_2: goto th_tail_call_2; \
  case OP_TAIL_CALL_3: goto th_tail_call_3; \
  case OP_TAIL_CALL_4: goto th_tail_call_4; \
  case OP_TAIL_CALL_5: goto th_tail_call_5; \
  case OP_TAIL_CALL_6: goto th_tail_call_6; \
  case OP_TAIL_CALL_PRIM_0: goto th_tail_call_prim_0; \
  case OP_TAIL_CALL_PRIM_1: goto th_tail_call_prim_1; \
  case OP_TAIL_CALL_PRIM_2: goto th_tail_call_prim_2; \
  case OP_TAIL_CALL_PRIM_3: goto th_tail_call_prim_3; \
  case OP_TAIL_CALL_PRIM_4: goto th_tail_call_prim_4; \
  case OP_TAIL_CALL_PRIM_5: goto th_tail_call_prim_5; \
  case OP_TAIL_CALL_PRIM_6: goto th_tail_call_prim_6; \
  case OP_APPLY_0: goto th_apply_0; \
  case OP_APPLY_1: goto th_apply_1; \
  case OP_APPLY_2: goto th_apply_2; \
  case OP_APPLY_3: goto th_apply_3; \
  case OP_APPLY_4: goto th_apply_4; \
  case OP_APPLY_5: goto th_apply_5; \
  case OP_APPLY_6: goto th_apply_6; \
  case OP_TAIL_APPLY_0: goto th_tail_apply_0; \
  case OP_TAIL_APPLY_1: goto th_tail_apply_1; \
  case OP_TAIL_APPLY_2: goto th_tail_apply_2; \
  case OP_TAIL_APPLY_3: goto th_tail_apply_3; \
  case OP_TAIL_APPLY_4: goto th_tail_apply_4; \
  case OP_TAIL_APPLY_5: goto th_tail_apply_5; \
  case OP_TAIL_APPLY_6: goto th_tail_apply_6; \
  case OP_GOTO: goto th_goto; \
  case OP_BRANCH: goto th_branch; \
  case OP_IADD: goto th_iadd; \
  case OP_ISUB: goto th_isub; \
  case OP_IMUL: goto th_imul; \
  case OP_IDIV: goto th_idiv; \
  case OP_IMOD: goto th_imod; \
  case OP_INEG: goto th_ineg; \
  case OP_INT_GREATER: goto th_int_greater; \
  case OP_INT_LESS: goto th_int_less; \
  case OP_INT_GREATER_OR_EQUAL: goto th_int_greater_or_equal; \
  case OP_INT_LESS_OR_EQUAL: goto th_int_less_or_equal; \
  case OP_INT_IS_POSITIVE: goto th_int_is_positive; \
  case OP_INT_IS_NON_NEGATIVE: goto th_int_is_non_negative; \
  case OP_INT_IS_NON_ZERO: goto th_int_is_non_zero; \
  case OP_FADD: goto th_fadd; \
  case OP_FSUB: goto th_fsub; \
  case OP_FMUL: goto th_fmul; \
  case OP_FDIV: goto th_fdiv; \
  case OP_FNEG: goto th_fneg; \
  case OP_FLOAT_GREATER: goto th_float_greater; \
  case OP_FLOAT_LESS: goto th_float_less; \
  case OP_FLOAT_GREATER_OR_EQUAL: goto th_float_greater_or_equal; \
  case OP_FLOAT_LESS_OR_EQUAL: goto th_float_less_or_equal; \
  case OP_FLOAT_IS_POSITIVE: goto th_float_is_positive; \
  case OP_FLOAT_IS_NON_NEGATIVE: goto th_float_is_non_negative; \
  case OP_FLOAT_IS_NON_ZERO: goto th_float_is_non_zero; \
  default: assert(false);
