import * as S from "@xieyuheng/sexp.js"

export const sexpConfig: S.Config = {
  keywords: [
    ["import", 1],
    ["import-as", 0],
    ["import-all", 0],
    ["exempt", 0],
    ["private", 0],
    ["claim", 1],
    ["admit", 1],
    ["define", 1],
    ["interface", 0],
    ["extend-interface", 1],
    ["define-interface", 1],
    ["define-data", 1],
    ["define-test", 1],
    ["define-type", 1],
    ["let", 1],
    ["let*", 1],
    ["the", 1],
    ["assert", 0],
    ["assert-not", 0],
    ["assert-the", 0],
    ["assert-equal", 0],
    ["assert-not-equal", 0],
    ["begin", 0],
    ["lambda", 1],
    ["match", 1],
    ["match-many", 1],
    ["pipe", 1],
    ["compose", 0],
    ["if", 1],
    ["when", 1],
    ["unless", 1],
    ["cond", 0],
    ["@list", 0],
    ["@record", 0],
    ["@set", 0],
    ["@hash", 0],
    ["polymorphic", 1],
  ],
}
