(declare-primitive-function meta-builtin/builtin/println)
(declare-primitive-function meta-builtin/builtin/closure-arg)

(define-function (add-n©closure ©closure x)
  (load-int zero 0)
  (call-prim-2 (prim meta-builtin/builtin/closure-arg) zero ©closure)
  (load-result n)
  (iadd result x n)
  (return result))

(define-function (make-add-n n)
  (make-closure closure (fn add-n©closure) (u16 1))
  (store-closure-arg closure (u16 0) n)
  (return closure))

(define-function (test)
  (load-int n 10)
  (call-1 (fn make-add-n) n)
  (load-result f)
  (load-int x 32)
  (apply-1 f x)
  (load-result r)
  (call-prim-1 (prim meta-builtin/builtin/println) r)
  (return-void))
