(assert-equal (list-get 0 [1 2 3]) 1)
(assert-equal (list-get 1 [1 2 3]) 2)
(assert-equal (list-get 2 [1 2 3]) 3)

(begin
  (= list [0 0 0])
  (assert-equal (list-get 0 list) 0)
  (assert-equal (list-get 1 list) 0)
  (assert-equal (list-get 2 list) 0)
  (= list (list-set 0 1 list))
  (= list (list-set 1 2 list))
  (= list (list-set 2 3 list))
  (assert-equal (list-get 0 list) 1)
  (assert-equal (list-get 1 list) 2)
  (assert-equal (list-get 2 list) 3))
