(import category-t "category.lisp")
(import functor-t "functor.lisp")
(import naturaltrans-formation-t "naturaltrans-formation.lisp")
(import isomorphism-t "isomorphism.lisp")
(import trivial-category-t "trivial-category.lisp")
