#pragma once

x_fn_0_t x_make_set;
x_fn_1_t x_is_any_set;
x_fn_1_t x_set_copy;
x_fn_1_t x_set_size;
x_fn_1_t x_set_is_empty;
x_fn_2_t x_set_is_member;
x_fn_2_t x_set_add_mut;
x_fn_2_t x_set_add;
x_fn_2_t x_set_delete_mut;
x_fn_2_t x_set_delete;
x_fn_1_t x_set_clear_mut;
x_fn_2_t x_set_union;
x_fn_2_t x_set_inter;
x_fn_2_t x_set_difference;
x_fn_2_t x_set_subset;
x_fn_2_t x_set_disjoint;
x_fn_1_t x_set_to_list;
