(include-all "function/index.lisp")
(include-all "conditional/index.lisp")
(include-all "optional/index.lisp")
(include-all "list/index.lisp")
(include-all "record/index.lisp")
(include-all "hash/index.lisp")
